# fly.toml app configuration file generated for dj-set-downloader on 2023-07-15T22:22:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dj-set-downloader"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
